spring.application.name=SpringBoot
spring.security.oauth2.client.registration.google.client-id=323449638220-ml1fmbfh0k4lfj0i8shfaj25lcamjssh.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.datasource.url=jdbc:sqlserver://localhost;databasename=figz;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd
spring.mvc.hiddenmethod.filter.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=antonin.mrtl.pr@gmail.com

spring.mail.password=sofoqrmqtvawnivv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

