spring.application.name=Ownly
server.servlet.session.timeout=300s

# Remplacez les valeurs ci-dessous par vos identifiants Google Cloud Console
spring.security.oauth2.client.registration.google.client-id=[VOTRE_CLIENT_ID]
spring.security.oauth2.client.registration.google.client-secret=[VOTRE_CLIENT_SECRET]

# La base de données doit être nommée "figz"
spring.datasource.url=jdbc:sqlserver://localhost;databasename=figz;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=[VOTRE_USER_SA]
spring.datasource.password=[VOTRE_MOT_DE_PASSE]

spring.mvc.hiddenmethod.filter.enabled=true

# Pour Gmail, utilisez un "Mot de passe d'application"
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=[VOTRE_EMAIL_GMAIL]
spring.mail.password=[VOTRE_MOT_DE_PASSE_APPLICATION]

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
server.servlet.session.timeout=300s
