-- Nettoyage préalable (ordre inverse des dépendances)
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS AUCTION;
DROP TABLE IF EXISTS ItemSold;
DROP TABLE IF EXISTS WITHDRAWAL;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS USERS;

-- Création des tables

CREATE TABLE CATEGORY (
                          category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(30) NOT NULL
);

CREATE TABLE USERS (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(30) NOT NULL,
                       lastName VARCHAR(30) NOT NULL,
                       firstName VARCHAR(30) NOT NULL,
                       email VARCHAR(50) NOT NULL,
                       numPhone VARCHAR(15),
                       street VARCHAR(40) NOT NULL,
                       postalCode VARCHAR(10) NOT NULL,
                       city VARCHAR(30) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       credit BIGINT NOT NULL,
                       admin BIT NOT NULL,
                       active BIT NOT NULL
);

CREATE TABLE WITHDRAWAL (
                            withdrawal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            street VARCHAR(30) NOT NULL,
                            postalCode VARCHAR(15) NOT NULL,
                            city VARCHAR(30) NOT NULL
);

CREATE TABLE ItemSold (
                          article_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          articleName VARCHAR(30) NOT NULL,
                          description VARCHAR(300) NOT NULL,
                          auctionStartDate DATE NOT NULL,
                          auctionEndDate DATE NOT NULL,
                          startingPrice BIGINT,
                          priceSale BIGINT,
                          user_id BIGINT NOT NULL,
                          category_id BIGINT NOT NULL,
                          withdrawal_id BIGINT NOT NULL
);

CREATE TABLE AUCTION (
                         auction_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         user_id BIGINT NOT NULL,
                         article_id BIGINT NOT NULL,
                         auctionDate TIMESTAMP NOT NULL,
                         auctionAmount BIGINT NOT NULL,
                         PRIMARY KEY (user_id, article_id)
);

CREATE TABLE ROLES (
                         user_id BIGINT NOT NULL,
                         "role" VARCHAR(50) NOT NULL,
                         PRIMARY KEY (user_id, "role")
);

-- Ajout des Contraintes (Foreign Keys)

ALTER TABLE ItemSold
    ADD CONSTRAINT articles_sold_categories_fk FOREIGN KEY (category_id)
        REFERENCES CATEGORY (category_id);

ALTER TABLE ItemSold
    ADD CONSTRAINT sales_user_fk FOREIGN KEY (user_id)
        REFERENCES USERS (user_id);

ALTER TABLE ItemSold
    ADD CONSTRAINT itemsold_withdrawal_fk FOREIGN KEY (withdrawal_id)
        REFERENCES WITHDRAWAL (withdrawal_id);

ALTER TABLE AUCTION
    ADD CONSTRAINT auction_user_fk FOREIGN KEY (user_id)
        REFERENCES USERS (user_id);

ALTER TABLE AUCTION
    ADD CONSTRAINT auction_articles_sold_fk FOREIGN KEY (article_id)
        REFERENCES ItemSold (article_id);

ALTER TABLE ROLES
    ADD CONSTRAINT fk_roles_users FOREIGN KEY (user_id)
        REFERENCES USERS(user_id);